services:
  postgres:
    image: postgres:16-alpine
    container_name: titan-db
    environment:
      POSTGRES_USER: titan
      POSTGRES_PASSWORD: titan_password
      POSTGRES_DB: titan_isp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: titan-redis
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: titan-api
    environment:
      DATABASE_URL: "postgresql://titan:titan_password@postgres:5432/titan_isp?schema=public"
      REDIS_URL: "redis://redis:6379"
      JWT_SECRET: "seu_secret_super_seguro"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: titan-web
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  postgres_data:
